variable "vpc_cidr" {}
variable "vpc_name" {}
variable "subnet_1_cidr" {}
variable "az1" {}
variable "subnet_1_name" {}
variable "subnet_2_cidr" {}
variable "az2" {}
variable "subnet_2_name" {}
variable "IGW_Name" {}
variable "subnet_3_cidr" {}
variable "az3" {}
variable "subnet_3_name" {}
variable "public_route_name" {}
variable "ami" {}
variable "key_name" {}
variable "instance_type" {}
variable "instance_name" {}